# Cho phép Redis kết nối từ mọi địa chỉ IP
bind 0.0.0.0

# Đặt mật khẩu truy cập (Thay 'duyphan123' bằng mật khẩu bạn muốn)
requirepass duyphan123

# Giới hạn bộ nhớ tối đa là 256MB
maxmemory 256mb
maxmemory-policy allkeys-lru

# Bật chế độ lưu dữ liệu xuống đĩa cứng sau mỗi 60 giây nếu có ít nhất 1 thay đổi
save 60 1